### PR TITLE
Fix `allow_blank` and `default` in conjunction with `in` option

### LINKED ISSUE #104: `default` option doesn't work when using `using`
When I tried setting up a scope like this:
```
has_scope :status, in: :report_options, default: 'any'
```

and hitting the controller action without any params, I noticed it was generating `status = NULL` in the where conditions.

I was expecting it to generate `status = 'any'` by default since no `params[:report_options][:status]` is present.

When I dug deeper with a debugger, it's sending nil to the scope is because it `value.values_at(*options[:using])` is indeed nil.

```
[159, 168] in gems/has_scope-0.7.2/lib/has_scope.rb
   159:     block = options[:block]
   160: 
   161:     if type == :boolean && !options[:allow_blank]
   162:       block ? block.call(self, target) : target.send(scope)
   163:     elsif value && options.key?(:using)
=> 164:       value = value.values_at(*options[:using])
   165:       block ? block.call(self, target, value) : target.send(scope, *value)
   166:     else
   167:       block ? block.call(self, target, value) : target.send(scope, value)
   168:     end

(byebug) value.values_at(*options[:using])
[nil]
```

I haven't dug any deeper yet to see how it's supposed to get the default value, but just wanted to report what I've found so far and suggest that it should probably be expected behavior for `default` to work with `using` too.

My workaround was to not use `in:` to tell `has_scope` to dig into the hash, but to use `type: :hash` and handle the digging into the hash and applying defaults manually myself in the block:
```
  has_scope :report_options, type: :hash do |controller, relation, hash|
    if value = hash[:active] || 'any'
      relation = relation.active(value)
    end
    ...
    relation
  end
```

### LINKED ISSUE #113: Hash sends "nil" values to scope even if allow_blank is not set to true
My setup:
User has 3 select inputs to choose different filter values (filter1, filter2, filter3).
I have nested params which look like:
```
{"utf8"=>"✓", "filter"=>{"show_discontinued"=>"true", "filter1"=>"value1", "filter2"=>"value2", "filter3"=>"value3"}, "commit"=>"", "page"=>"", "size"=>"50", "sort"=>"", "direction"=>""}
```

The scopes are set on filter values `filter1`, `filter2`, `filter3` 

To pass the nested hash value to scope, I use `in: filter` which works perfectly fine:
controller:
```
has_scope :filter1, in: :filter
```

model: 
```
scope :filter1, -> value { where('table.association_id = ?', value) }
```

printing `current_scopes`:
```
{:filter=>{"show_discontinued"=>"true", "filter1"=>"18"}}
```

Till here things work fine.

This issue starts now:
When user selects the "All" option in the select input (which has a blank value), the nil value is passed to scope which results in following query

```
WHERE (table.association_id = NULL)
```

So the query looks for null matches against the column defined in the scope. I don't have any null values for `association_id` so the it returns 0 records.

params look like:
```
{"utf8"=>"✓", "filter"=>{"filter1"=>"", "filter2"=>"", "filter3"=>""}, "commit"=>"", "page"=>"", "size"=>"50", "sort"=>"", "direction"=>""}
```

printing `current_scopes`:
```
{:filter=>{"show_discontinued"=>"true"}}
```

This behaviour is only witnessed when `filter` contains other values as above. If I remove all filters, then current_scopes becomes `{}` which works fine.

Based on the Readme, I expect that when the value is nil or not present, it should not call the scope - unless `allow_blank` is set to true.
This works fine for values which have string or integer type and not hash.

Let me know if I my understanding is not correct and there's some way to make it work.

Note: Currently, I am checking for nil values in the scope itself as a workaround:
```
scope :filter1, -> value { where('table.association_id = ?', value)  if value.present? }
```

### PR DESCRIPTION
**Pull request by carlosantoniodasilva**
When the `in` option received a blank value, it was still applying the scope incorrectly if the params contained the outer key, as described in #113. We weren't properly verifying whether the nested params values were blank, and not respecting the `allow_blank` option either in that case.

When the `in` option was used with a `default`, the default wasn't being applied. The reason is because the `in` option is a shortcut for a type=hash + using scope config, and that expects a default that is also a hash, as detailed in #104. But you'd expect to pass a single default (like a string value) in that case, and that makes sense, but it was being discarded due to not matching the expected value to apply the scope. Now we covent the given default to the expected hash under the hood, so it should be applied correctly.

Hopefully closes #104 and fixes #113.

### CODE REVIEW

**Comment by nasaabg** [comment]
Hi, @carlosantoniodasilva have tested your branch with my code, but I am not sure if it is expected result:

I have scope like this:
```ruby
scope :by_sth, ->(a = 'default1', b = 'default2', c = 'default3') { where(foo: a, bar: b, boo: c) }
```
In my Controller:
```ruby
    has_scope :by_sth, using: %i[a b c], type: :hash, as: :filters, allow_blank: true
```

and request like this:
`api/xyz?filters[a]=janek&filters[b]=kowalski`

Then I expected to have query like `select * from X where a = 'janek' and b = 'kowalski' and c = 'default3'`
unfortunately is seems that the `by_sth` scope was called passing `nil` as missing (blank) arg like this:
`by_sth('janek', 'kowalski', nil)` because I got query like this:
 `select * from X where a = 'janek' and b = 'kowalski' and c = null`
I expected deafult value to be usesd for `c`

When I remove `allow_blank` then scope `by_sth` is completely omitted even I send 2 out of 3 params

**Comment by nasaabg** [comment]
When I changed definitions in Controller to:
```ruby
 has_scope :by_sth, using: %i[a b c], in: :filters, allow_blank: true
```
It seems that `nil` stopped to be sent as an argument, but on the other hand, those params `filters[a]=janek&filters[b]=kowalski` were not recognized. Perhaps I can not use `using` and `in`

**Comment by nasaabg** [comment]
@carlosantoniodasilva did you have time to look into it?

**Comment by carlosantoniodasilva** [comment]
@nasaabg Apologies again for the delay getting back to you here.

It seems like has_scope is doing the right thing there. If it's using 3 arguments, it will always send down to the method all of them, or none (and then all of the defaults should be picked)

If for example the missing value was filters :b, there's no way to call that method (or proc/lambda) in a way that `default2` would be used. has_scope would have to call it passing down the 3 args, and the second one (`b`) would have to be sent `nil`.

In your example, `c` is the one "missing" a value, but the call would still be delegated down with the three arguments. I hope that makes sense, please let me know if you have any questions.

Also please note that the changes in this PR are meant to improve this for the usage with the `:in` option.

**Pull request merged**
